# Generated by Django 4.1.13 on 2024-01-09 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Caducidad',
            field=models.CharField(help_text='Formato: 00/00', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='facturacion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_ID',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('opcion1', 'MasterCard'), ('opcion2', 'Visa'), ('opcion3', 'Paypal')], max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='titular',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='puntaje_valoracion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
