# Generated by Django 4.1.13 on 2024-01-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_producto_puntaje_valoracion_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='user',
        ),
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.valoracion'),
        ),
    ]
