# Generated by Django 4.1.13 on 2024-01-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_valoracion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='valor',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
