# Generated by Django 4.1.13 on 2024-01-22 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_producto_valor_valoracion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='puntaje_valoracion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=10)]),
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
