# Generated by Django 4.1.13 on 2024-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_cliente_caducidad_remove_cliente_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
